### ISSUE TITLE
Upgrade to 'null-safety'

### ISSUE THREAD

**Issue by kostaa** [james-alex/xml_parser#3]
Hi There,
Would you be able to upgrade this library to sdk: ">=2.12.0-0 <3.0.0" / null-safety?
Many thanks!

**Comment by mikeborodin** [comment]
Also interested in null-safety, are there any plans to support it? :)

**Comment by james-alex** [comment]
My apologies for the delay here. xml_parser has now been migrated to null-safety as of `v1.0.0`, now on [pub.dev](https://pub.dev/packages/xml_parser).
